import { NutDictionary, IngredientCategoryDictionary } from './interface';

// 영양소 영문-> 한글, 분류 mapping
export const nutritionDictionary: NutDictionary = {
  biotin: { name: '비오틴(비타민 B7)', category: 3, scale: '㎍' },
  calcium: { name: '칼슘', category: 4, scale: 'mg' },
  carbohydrate: { name: '탄수화물', category: 1, scale: 'g' },
  cholesterol: { name: '콜레스트롤', category: 5, scale: 'mg' },
  copper: { name: '구리', category: 4, scale: 'mg' },
  dietaryFiber: { name: '식이섬유', category: 1, scale: 'g' },
  fat: { name: '지방', category: 2, scale: 'g' },
  folicAcid: { name: '엽산(비타민 B9)', category: 3, scale: '㎍' },
  iodine: { name: '아이오딘(요오드)', category: 4, scale: '㎍' },
  iron: { name: '철분', category: 4, scale: 'mg' },
  kcal: { name: '칼로리', category: 5, scale: 'Kcal' },
  magnesium: { name: '마그네슘', category: 4, scale: 'mg' },
  manganese: { name: '망간', category: 4, scale: 'mg' },
  moisture: { name: '수분', category: 5, scale: 'g' },
  molybdenum: { name: '몰리브데넘', category: 4, scale: '㎍' },
  niacin: { name: '나이아신(비타민 B3)', category: 3, scale: 'mg' },
  omega3FattyAcids: { name: '오메가 3 지방산', category: 2, scale: 'g' },
  pantothenicAcid: { name: '판토텐산(비타민 B5)', category: 3, scale: 'mg' },
  phosphorus: { name: '인', category: 4, scale: 'mg' },
  potassium: { name: '칼륨', category: 4, scale: 'mg' },
  protein: { name: '단백질', category: 0, scale: 'g' },
  selenium: { name: '셀레늄', category: 4, scale: '㎍' },
  sodium: { name: '나트륨', category: 4, scale: 'mg' },
  sugar: { name: '설탕', category: 1, scale: 'g' },
  transFattyAcid: { name: '트랜스지방산', category: 2, scale: 'g' },
  vitaminB12: { name: '비타민 B12', category: 3, scale: '㎍' },
  vitaminB6: { name: '비타민 B6', category: 3, scale: 'mg' },
  vitaminC: { name: '비타민 C', category: 3, scale: 'mg' },
  vitaminD: { name: '비타민 D', category: 3, scale: 'mg' },
  vitaminE: { name: '비타민 E', category: 3, scale: 'mg' },
  vitaminK: { name: '비타민 K', category: 3, scale: 'mg' },
  zinc: { name: '아연', category: 4, scale: 'mg' },
};

export const ingredientCategoryDictionary: IngredientCategoryDictionary = {
  '곡류 및 가공품': 0,
  '감자 및 전분류': 1,
  두류: 2,
  '견과류 및 종실류': 3,
  채소류: 4,
  버섯류: 5,
  과실류: 6,
  해조류: 7,
  육류: 8,
  난류: 9,
  수산물: 10,
  '우유 및 유제품류': 11,
  차류: 12,
  음료류: 13,
  주류: 14,
  당류: 15,
  조미료류: 16,
  유지류: 17,
  기타: 18,
};
