import { NutDictionary } from './interface';

// 영양소 영문-> 한글, 분류 mapping
export const nutritionDictionary: NutDictionary = {
  biotin: { name: '비오틴(비타민 B7)', category: 3 },
  calcium: { name: '칼슘', category: 4 },
  carbohydrate: { name: '탄수화물', category: 1 },
  cholesterol: { name: '콜레스트롤', category: 5 },
  copper: { name: '구리', category: 4 },
  dietaryFiber: { name: '식이섬유', category: 1 },
  fat: { name: '지방', category: 2 },
  folicAcid: { name: '엽산(비타민 B9)', category: 3 },
  iodine: { name: '아이오딘(요오드)', category: 4 },
  iron: { name: '철분', category: 4 },
  kcal: { name: '칼로리', category: 5 },
  magnesium: { name: '마그네슘', category: 4 },
  manganese: { name: '망간', category: 4 },
  moisture: { name: '수분', category: 5 },
  molybdenum: { name: '몰리브데넘', category: 4 },
  niacin: { name: '나이아신(비타민 B3)', category: 3 },
  omega3FattyAcids: { name: '오메가 3 지방산', category: 2 },
  pantothenicAcid: { name: '판토텐산(비타민 B5)', category: 3 },
  phosphorus: { name: '인', category: 4 },
  potassium: { name: '칼륨', category: 4 },
  protein: { name: '단백질', category: 0 },
  selenium: { name: '셀레늄', category: 4 },
  sodium: { name: '나트륨', category: 4 },
  sugar: { name: '설탕', category: 1 },
  transFattyAcid: { name: '트랜스지방산', category: 2 },
  vitaminB12: { name: '비타민 B12', category: 3 },
  vitaminB6: { name: '비타민 B6', category: 3 },
  vitaminC: { name: '비타민 C', category: 3 },
  vitaminD: { name: '비타민 D', category: 3 },
  vitaminE: { name: '비타민 E', category: 3 },
  vitaminK: { name: '비타민 K', category: 3 },
  zinc: { name: '아연', category: 4 },
};
