import {
  NutDictionary,
  IngredientCategoryDictionary,
  IngredientColorDictionary,
} from './interface';

// 영양소 영문-> 한글, 분류 mapping
export const nutritionDictionary: NutDictionary = {
  biotin: { name: '비오틴(비타민 B7)', category: 3, scale: '㎍' },
  calcium: { name: '칼슘', category: 4, scale: 'mg' },
  carbohydrate: { name: '탄수화물', category: 1, scale: 'g' },
  cholesterol: { name: '콜레스트롤', category: 5, scale: 'mg' },
  copper: { name: '구리', category: 4, scale: 'mg' },
  dietaryFiber: { name: '식이섬유', category: 1, scale: 'g' },
  fat: { name: '지방', category: 2, scale: 'g' },
  folicAcid: { name: '엽산(비타민 B9)', category: 3, scale: '㎍' },
  iodine: { name: '아이오딘(요오드)', category: 4, scale: '㎍' },
  iron: { name: '철분', category: 4, scale: 'mg' },
  kcal: { name: '칼로리', category: 5, scale: 'Kcal' },
  magnesium: { name: '마그네슘', category: 4, scale: 'mg' },
  manganese: { name: '망간', category: 4, scale: 'mg' },
  moisture: { name: '수분', category: 5, scale: 'g' },
  molybdenum: { name: '몰리브데넘', category: 4, scale: '㎍' },
  niacin: { name: '나이아신(비타민 B3)', category: 3, scale: 'mg' },
  omega3FattyAcids: { name: '오메가 3 지방산', category: 2, scale: 'g' },
  pantothenicAcid: { name: '판토텐산(비타민 B5)', category: 3, scale: 'mg' },
  phosphorus: { name: '인', category: 4, scale: 'mg' },
  potassium: { name: '칼륨', category: 4, scale: 'mg' },
  protein: { name: '단백질', category: 0, scale: 'g' },
  selenium: { name: '셀레늄', category: 4, scale: '㎍' },
  sodium: { name: '나트륨', category: 4, scale: 'mg' },
  sugar: { name: '설탕', category: 1, scale: 'g' },
  transFattyAcid: { name: '트랜스지방산', category: 2, scale: 'g' },
  vitaminB12: { name: '비타민 B12', category: 3, scale: '㎍' },
  vitaminB6: { name: '비타민 B6', category: 3, scale: 'mg' },
  vitaminC: { name: '비타민 C', category: 3, scale: 'mg' },
  vitaminD: { name: '비타민 D', category: 3, scale: 'mg' },
  vitaminE: { name: '비타민 E', category: 3, scale: 'mg' },
  vitaminK: { name: '비타민 K', category: 3, scale: 'mg' },
  zinc: { name: '아연', category: 4, scale: 'mg' },
};

export const ingredientCategoryDictionary: IngredientCategoryDictionary = {
  '곡류 및 가공품': 0,
  '감자 및 전분류': 1,
  두류: 2,
  '견과류 및 종실류': 3,
  채소류: 4,
  버섯류: 5,
  과실류: 6,
  해조류: 7,
  육류: 8,
  난류: 9,
  수산물: 10,
  '우유 및 유제품류': 11,
  차류: 12,
  음료류: 13,
  주류: 14,
  당류: 15,
  조미료류: 16,
  유지류: 17,
  기타: 18,
};

export const ingredientCategoryColor: IngredientColorDictionary = {
  '곡류 및 가공품': { primary: '#F1B826', secondary: '#8DEA17 ' },
  '감자 및 전분류': { primary: '#DD9B38', secondary: '#F9E6C8' },
  두류: { primary: '#33691E', secondary: '#DCE775' },
  '견과류 및 종실류': { primary: '#FFDAA4', secondary: '#FC5E68' },
  채소류: { primary: '#FF3A1A', secondary: '#79E645' },
  버섯류: { primary: '#B27214', secondary: '#F9DCB2' },
  과실류: { primary: '#FE9F81', secondary: '#A4D31F' },
  해조류: { primary: '#2D9547', secondary: '#85BB40' },
  육류: { primary: '#D2492A', secondary: '#FAE6C7' },
  난류: { primary: '#EDE6CF', secondary: '#FFB72B' },
  수산물: { primary: '#59CAFC', secondary: '#00B1FF' },
  '우유 및 유제품류': { primary: '#526FFF', secondary: '#FFFFFF' },
  차류: { primary: '#FF7171', secondary: '#FFFFFF' },
  음료류: { primary: '#E3283F', secondary: '#FFFFFF' },
  주류: { primary: '#99130C', secondary: '#BBE9FD' },
  당류: { primary: '#A66335', secondary: '#EE4129' },
  조미료류: { primary: '#84BCEE', secondary: '#C8BC78' },
  유지류: { primary: '#FDD44B', secondary: '#84BD93' },
  기타: { primary: '#000', secondary: '#fff' },
};

export const largeCategoryDictionary: IngredientCategoryDictionary = {
  '곡류 및 채소': 0,
  육류: 1,
  수산물: 2,
  유제품: 3,
  음료: 4,
  '조미료 및 기름': 5,
  기타: 6,
};
